export const SAVE_TRENDING_DATA = 'SAVE_TRENDING_DATA';
export const SAVE_TRENDING_MORE_DATA = 'SAVE_TRENDING_MORE_DATA';
export const SAVE_MODAL_DATA = 'SAVE_MODAL_DATA';
export const CLEAR_MODAL_DATA = 'CLEAR_MODAL_DATA';